### PyTorch Basics - Tensors and Data Structures


In [63]:
import torch
import numpy as np

In [2]:
x = torch.empty(1)
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # 1 D with 3 elements
print(x)

tensor([7.0065e-45, 0.0000e+00, 0.0000e+00])


In [4]:
x = torch.empty(2, 3) # 2 * 3 matrix
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.empty(2, 3, 3) # 3 * 3 matrix
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [11]:
x = torch.empty(1, 3, 3, 3) # 4 * 3 matrix
#print(x)

In [12]:
x = torch.ones(2,2)
print(x.dtype) #default float 32

torch.float32


In [15]:
x = torch.zeros(2,2, dtype = torch.float16)
print(x.dtype)

torch.float16


In [17]:
x = torch.ones(2,2, dtype = torch.float16)
print(x.size)

<built-in method size of Tensor object at 0x121272e10>


In [18]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


Some basic operations

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x,y)


tensor([[0.1536, 0.8916],
        [0.2744, 0.4880]]) tensor([[0.2043, 0.2026],
        [0.3956, 0.8747]])
tensor([[0.3579, 1.0942],
        [0.6700, 1.3626]])


In [22]:
z = x + y
z = torch.add(x,y)
print(z)

tensor([[0.3579, 1.0942],
        [0.6700, 1.3626]])


In [24]:
z = x @ y # dot product Matrix Mult
print(z)

tensor([[0.3841, 0.8109],
        [0.2491, 0.4824]])


In [36]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x - y
z = torch.add(x, y)
print(z)
y.add_(x)

tensor([[0.0968, 1.6292],
        [0.0675, 0.8703]])


tensor([[0.0968, 1.6292],
        [0.0675, 0.8703]])

In [43]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x - y
z = torch.sub(x, y)
z = torch.sub(x, y)
y.sub_(x)

tensor([[-0.6516, -0.2231],
        [ 0.1749,  0.1207]])

In [42]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x * y
z = torch.mul(x, y)
y.mul_(x)

tensor([[0.3163, 0.2764],
        [0.0253, 0.0998]])

In [41]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x / y
z = torch.div(x, y)
y.div_(x)

tensor([[1.6770, 0.0620],
        [1.0061, 1.0394]])

In [45]:
# Slicing

x = torch.rand(5, 3)
print(x)
print(x[:,1])

tensor([[0.7292, 0.4343, 0.4195],
        [0.9464, 0.3485, 0.0355],
        [0.9063, 0.4675, 0.2910],
        [0.6645, 0.0571, 0.2148],
        [0.9441, 0.3499, 0.7218]])
tensor([0.4343, 0.3485, 0.4675, 0.0571, 0.3499])


In [46]:
print(x[1,1])

tensor(0.3485)


In [48]:
print(x[2,-1])

tensor(0.2910)


In [49]:
print(x[-2,-1])

tensor(0.2148)


In [56]:
# Resizing tensors

x = torch.rand(4, 4)
print(x)

y = x.view(-1,8)
print(y.size())

y = x.view(16)
print(y.size())


tensor([[0.4857, 0.2919, 0.9086, 0.4099],
        [0.2693, 0.9914, 0.0888, 0.3989],
        [0.6788, 0.9780, 0.2262, 0.9591],
        [0.4481, 0.5270, 0.3042, 0.1438]])
torch.Size([2, 8])
torch.Size([16])


In [61]:
# Moving between Tensors and Numpy Arrays

a = torch.ones(5) # Moving from a tensor to a numpy - 
print(a)
b = a.numpy()
print(type(b))

a.add_(1) # be careful on a CPU they will both be in the same memory location so mods will impact both PyTorch and Numpy objects
print(b)
print(a) # both have a 1 added because they are in the same mem loc

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])


In [77]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

#If we modify the np array you will see the change in the tensor

a += 2
print(a)
print(b)

if torch.cuda.is_available():
    device = torch.device("cuda") # Assign a CUDA device
    x = torch.ones(5, device = device) # Point the x array to the GPU
    y = torch.ones(5)
    
    y = y.to(device) #this moves it to the device
    
    z = x + y # this would be performed on the GPU but you would get numpy errors as they dont work on a gpu
    z = z.to("cpu") # Moving then z vector back to the CPU


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [78]:
# Gradient Calculations

x = torch.ones(5, requires_grad = True) #If you ever need the gradient to optimise a function and calculate the loss you will need this enabled. 

